FROM maven:latest as build
RUN apt update && apt install -y git
RUN git clone https://github.com/geoserver/geoserver.git /app
#check structure after clone
RUN ls -la /app
WORKDIR /app/src
RUN mvn -e package -DskipTests