version: '3.3'

services:
  build-service:
    image: "158.160.145.70:8123/mydockerrepo/geoserver_build:latest"  
    container_name: geoserver_build
    volumes:
      - .:/app  
    command: mvn -e package -DskipTests 
    networks:
      - app-network

  prod-service:
    image: "158.160.145.70:8123/mydockerrepo/geoserver_prod:latest" 
    container_name: geoserver_prod
    ports:
      - "8081:8080"  
    depends_on:
      - build-service  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

